baseURL = "https://wangoon.github.io/"
languageCode = "en-us"
title = "wangoon studio"
theme = "hyde"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
publishDir = "wangoon.github.io"

